title:              Computational Intelligence Lab
email:              your-email@example.com
description:        SUSTech
author:             cwy
baseurl:            "/"
url:                "https://lingxiaomeng.github.io"

# Social Profiles
twitter_username:   xxx
github_username:    xxx
facebook_username:  xxx
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
